### ISSUE TITLE
Limited access in Network Session

### ISSUE THREAD

**Issue by vaIerika** [GoodRequest/GoodNetworking#21]
Session and configuration are now private, it limits area of developers' implementation. 

Example: updating GoodNetworking on Kia project leads to a problem that "flush url cache" of the session configuration cannot be supported: 
'session.sessionConfiguration.urlCache?.removeAllCachedResponses()'.

**Comment by andrej-jasso** [comment]
Please create an PR in GoodNetworking making the session sessionConfiguration parameter public. I agree you should be able to access it for these reason.

**Comment by plajdo** [comment]
@vaIerika https://github.com/GoodRequest/GoodNetworking/pull/20/files

would this help?
